# Generated by Django 4.1.4 on 2023-03-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_alter_materia_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.CharField(choices=[('', '-------------'), ('1', '1er Semestre'), ('2', '2do Semestre'), ('3', '3er Semestre'), ('4', '4to Semestre'), ('5', '5to Semestre'), ('6', '6to Semestre'), ('7', '7mo Semestre'), ('8', '8vo Semestre'), ('9', '9no Semestre')], max_length=2),
        ),
    ]
