# Generated by Django 4.1.4 on 2023-03-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_academicas', '0001_initial'),
        ('materias', '0003_alter_materia_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='unidades_academicas.programaacademico', verbose_name='Programa Academico'),
            preserve_default=False,
        ),
    ]
