# Generated by Django 4.1.4 on 2023-03-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='id',
        ),
        migrations.AlterField(
            model_name='horario',
            name='clave',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Clave'),
        ),
    ]
