# Generated by Django 4.1.4 on 2023-03-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades_academicas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula')),
                ('rfc', models.CharField(max_length=13, verbose_name='R.F.C')),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='perfiles', verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula')),
                ('apellido_paterno', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='perfiles', verbose_name='Foto de perfil')),
                ('fecha_nacimiento', models.DateField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades_academicas.programaacademico', verbose_name='Programa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
