# Generated by Django 4.1.4 on 2023-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alumno_estado_alumno_municipio_docente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de perfil'),
        ),
    ]
