# Generated by Django 4.1.4 on 2023-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_alumno_avatar_alter_docente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='apellido_materno',
            field=models.CharField(default='apellido_example', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='nombre',
            field=models.CharField(default='name_example', max_length=150),
            preserve_default=False,
        ),
    ]
